### ISSUE TITLE
[Feature request] add blur effect

### ISSUE THREAD

**Issue by tomshoo** [sunwxg/gnome-shell-extension-unlockDialogBackground#18]
So far, this extension works great but, It would be even great if it had the ability to blur the background on the lock screen before the dialog box. Could this be implemented?

**Comment by sunwxg** [comment]
But if you don't implement this extension, the background is blurred when showing dialog and time. What's difference between them?

**Comment by theEndurance-del** [comment]
> But if you don't implement this extension, the background is blurred when showing dialog and time. What's the difference between them?

I am actually trying to have a different wallpaper on the lock screen and it is kind of partially bright hence when the normal lockscreen with clock is displayed due to lack of blur I am not able to see the clock. That is why I am trying to achieve blur, So that the wallpaper is visible but also due to the blur I can see my clock

**Comment by sunwxg** [comment]
Yes, the bright color doesn't adapt the lock screen background. I will consider it.
